/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CostoDAO;
import controller.HabitacionDAO;
import dto.CostoDTO;
import dto.HabitacionDTO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author slaye
 */
public class Habitacion extends javax.swing.JDialog {

    /**
     * Creates new form Reserva
     */
    private String action;
    private int id;
    static private view.Habitaciones parent;
    private HabitacionDAO dao = new HabitacionDAO();
    private model.Habitacion hb;
    private CostoDAO cdao = new CostoDAO();
    
    
    
    //comboBox.addItem(new ComboItem("Visible String 1", "Value 1"));
    
    
    
    public Habitacion(view.Habitaciones parent, boolean modal, String action, int id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.parent = parent;
        this.action = action;
        this.id = id; 
        
         List<Object> costos  = cdao.getComboBox();
         
        for(Object costo_uncast : costos){
            CostoDTO costo = (CostoDTO) costo_uncast;
            cbx_costo.addItem(costo.getCosto());
        }
        
        loadHabitacion();
        
    }
    
      
    private void loadHabitacion(){
        if(action == "EDIT"){
            hb = new model.Habitacion();
            hb = (model.Habitacion)dao.getById(id);
            txt_ubicacion.setText(hb.getUbicacion());
            int a = hb.getAcomodacion();
            txt_acomodacion.setText(Integer.toString(a));
            
          
            int i;
            int t;
            String v;
            
            i= 0;
            t = cbx_costo.getItemCount();
            while(i < t){
            cbx_costo.setSelectedIndex(i);
            v = cbx_costo.getSelectedItem().toString();
            if(v.equals(hb.getCosto_d())){
                i = t;
                }
            i= i + 1;
            }
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        sqlDateModel1 = new org.jdatepicker.impl.SqlDateModel();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        utilDateModel2 = new org.jdatepicker.impl.UtilDateModel();
        utilCalendarModel1 = new org.jdatepicker.impl.UtilCalendarModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_fecha_reserva2 = new javax.swing.JLabel();
        lbl_fecha_reserva3 = new javax.swing.JLabel();
        lbl_fecha_reserva4 = new javax.swing.JLabel();
        cbx_costo = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        txt_ubicacion = new javax.swing.JTextField();
        txt_acomodacion = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_fecha_reserva2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_fecha_reserva2.setText("Costo");

        lbl_fecha_reserva3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_fecha_reserva3.setText("Ubicacion");

        lbl_fecha_reserva4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_fecha_reserva4.setText("Acomodacion");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_acomodacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_acomodacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fecha_reserva4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fecha_reserva2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fecha_reserva3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbx_costo, 0, 176, Short.MAX_VALUE)
                                    .addComponent(txt_ubicacion)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_acomodacion)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha_reserva3)
                    .addComponent(txt_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha_reserva4)
                    .addComponent(txt_acomodacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha_reserva2)
                    .addComponent(cbx_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_guardar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:                                        
        // TODO add your handling code here:
           if(action.equals("NEW")){
            boolean validacion = validar();
            if(validacion){
                int costo_id_pos= cbx_costo.getSelectedItem().toString().indexOf('-');
                int costo_id_val = Integer.parseInt(cbx_costo.getSelectedItem().toString().substring(0, costo_id_pos));
                String ubicacion = txt_ubicacion.getText() ;
                String acomodacion = txt_acomodacion.getText();
                
                model.Habitacion newHabitacion = new model.Habitacion();
                newHabitacion.setUbicacion(ubicacion);
                newHabitacion.setAcomodacion(Integer.parseInt(acomodacion));
                newHabitacion.setCosto_id(costo_id_val);
                
                boolean operacion = dao.insert(newHabitacion);
                if(operacion){
                    parent.refreshTabla();
                    this.dispose();
                }
            }
        }
        if(action.equals("EDIT")){
            boolean validacion = validar();
            if(validacion){
                model.Habitacion hbs = new model.Habitacion(hb.getId());
      
                
                int costo_id_pos= cbx_costo.getSelectedItem().toString().indexOf('-');
                int costo_id_val = Integer.parseInt(cbx_costo.getSelectedItem().toString().substring(0, costo_id_pos));
                String ubicacion = txt_ubicacion.getText() ;
                String acomodacion = txt_acomodacion.getText();
                
                hbs.setUbicacion(ubicacion);
                hbs.setAcomodacion(Integer.parseInt(acomodacion));
                hbs.setCosto_id(costo_id_val);
                boolean operacion = dao.update(hbs);
                if(operacion){
                    parent.refreshTabla();
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_acomodacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_acomodacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_acomodacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Habitacion dialog = new Habitacion(new view.Habitaciones(), true,"",0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JComboBox<String> cbx_costo;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_fecha_reserva2;
    private javax.swing.JLabel lbl_fecha_reserva3;
    private javax.swing.JLabel lbl_fecha_reserva4;
    private org.jdatepicker.impl.SqlDateModel sqlDateModel1;
    private javax.swing.JTextField txt_acomodacion;
    private javax.swing.JTextField txt_ubicacion;
    private org.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    private org.jdatepicker.impl.UtilDateModel utilDateModel2;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        
        String ubicacion = txt_ubicacion.getText();
        String acomodacion = txt_acomodacion.getText(); 
         if(ubicacion.equals("") || ubicacion.equals(null)){
            JOptionPane.showMessageDialog(parent, "Debe Ingresar la ubicacion", "ERROR DE VALIDACIÓN", JOptionPane.ERROR_MESSAGE);
            return false;
        }
         if(acomodacion.equals("") || acomodacion.equals(null)){
            JOptionPane.showMessageDialog(parent, "Debe ingresar la acomodacion", "ERROR DE VALIDACIÓN", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    } 
}
