/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.HuespedDAO;
import controller.ReservasDAO;
import dto.HuespedDTO;
import dto.ReservasDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author slaye
 */
public class Menu extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private ReservasDAO reservasDAO = new ReservasDAO();
    private HuespedDAO huespedDAO = new HuespedDAO();
    private String current;

    /**
     * Creates new form Registro
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    /*
    public Registro(view.Login login) {
        initComponents();
        goHuesped();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        login.dispose();
    }*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btn_huesped = new javax.swing.JMenu();
        btn_habitacion = new javax.swing.JMenu();
        btn_reservas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_huesped.setText("Huesped");
        btn_huesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_huespedMouseClicked(evt);
            }
        });
        jMenuBar1.add(btn_huesped);

        btn_habitacion.setText("Habitaciones");
        btn_habitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_habitacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(btn_habitacion);

        btn_reservas.setText("Reservas");
        btn_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reservasMouseClicked(evt);
            }
        });
        btn_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservasActionPerformed(evt);
            }
        });
        jMenuBar1.add(btn_reservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void btn_huespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huespedMouseClicked
      // TODO add your handling code here:
        view.Huespedes p1 = new Huespedes();
        p1.setVisible(true);  
    }//GEN-LAST:event_btn_huespedMouseClicked

    private void btn_reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasMouseClicked
        // TODO add your handling code here:
        
        view.Reservas p1 = new Reservas();
        p1.setVisible(true);  
    }//GEN-LAST:event_btn_reservasMouseClicked

    private void btn_habitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_habitacionMouseClicked
        // TODO add your handling code here:
        
        view.Habitaciones p1 = new Habitaciones();
        p1.setVisible(true);  
    }//GEN-LAST:event_btn_habitacionMouseClicked

    private void btn_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btn_habitacion;
    private javax.swing.JMenu btn_huesped;
    private javax.swing.JMenu btn_reservas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
